name: release pkg

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build pkg
        run: |
          chmod +x client-macos/build_pkg.sh
          ./client-macos/build_pkg.sh
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.pkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
